### ISSUE TITLE
Release 0.16.0

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polyserve#143]

**Comment by biaggi** [comment]
I'm interested in some features contained in this pre-release version, do you have any estimation on when 0.16.0 version is going to be available?

Can I help somehow?

Regards

**Comment by FredKSchott** [comment]
`npm install polyserve@next` will let you try out the latest pre-release versions, you can see whats new in the CHANGELOG

**Comment by biaggi** [comment]
@FredKSchott Thank you, it worked like charm :)

**Comment by abdonrd** [comment]
What happened with this release?

**Comment by abdonrd** [comment]
@justinfagnani to close?

**Comment by FredKSchott** [comment]
Yes!
