### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by martijnjanssen** [Polymer/polyserve#154]
The `npm install` command is currently failing due to a ?versioning? issue in ~polymer.json~ package.json. It appears that [this](https://github.com/Polymer/polyserve/pull/135#discussion-diff-95779145R30) fixes the issue.

**Comment by tony19** [comment]
I think you meant `package.json` :)
Updating `@types/node` to `^6.0.0` fixes the problem (as @TimvdLippe pointed out).
