### ISSUE TITLE
Always compile for MSEdge <= 38

### ISSUE THREAD

**Issue by valdrinkoshi** [Polymer/polyserve#161]
In Microsoft Edge 38.14393.0.0 (Microsoft EdgeHTML 14.14393), ES6 constructor returns class instead of an instance (see https://github.com/Microsoft/ChakraCore/issues/1496).
In this case polyserve should compile resources.

**Comment by aomarks** [comment]
Re-opening since my PR was checking the wrong versioning scheme (user agent contains EdgeHTML version, not main release version).
