### ISSUE TITLE
Inject es5 loader stanza into entrypoint html when serving es5 compiled JS.

### ISSUE THREAD

**Issue by usergenic** [Polymer/polyserve#164]
See https://github.com/Polymer/polymer-cli/issues/627 for the proposed solution.

May need to do more than inject (i.e. may need to shuffle order-dependent imperatives like scripts, styles and html imports) all down into the body after the loader.

**Comment by FredKSchott** [comment]
To whoever implements this: Instead of duplicating what polymer-build is doing and trying to keep parity, I'd like to see polyserve leverage polymer-build internally.

**Comment by justinfagnani** [comment]
Ideally polyserve should never need to do this, since it should only compile for browsers that don't support native Custom Elements.
