### ISSUE TITLE
JS is compiled for Chrome in device emulation mode

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polyserve#170]
Chrome changes the UA to match the device it's emulating, and the in auto-compile mode we do the wrong thing...

**Comment by usergenic** [comment]
Given that compilation is driven off of UA, what is the *right* thing to do?

**Comment by justinfagnani** [comment]
I tried to figure out a way to see from the UA string that the browser is really Chrome, and it doesn't look like there is. I think now we should just inject the custom-elements-es5-adapter

**Comment by FredKSchott** [comment]
I don't think it's worth fighting with the browser on this one. If a browser is trying to convince us it's iOS, we should believe it

**Comment by justinfagnani** [comment]
That's what I was saying

**Comment by justinfagnani** [comment]
This is being addressed in #179
