### ISSUE TITLE
Should the transform middleware bind to the response object (OutgoingMessage)?

### ISSUE THREAD

**Issue by akc42** [Polymer/polyserve#191]
This is a tentative issue in that I am not actually trying this in Polyserve at the moment, but it does seem wrong.  I have taken a much bastardised version of this code to implement the on the fly transform in my own application which is using the http2 npm module to provide a server.  this http2 module provides a number of prototype extensions to OutgoingMessage, 

The transform middleware replaces `response.write` and `response.end` with some local functions and in certain circumstances they call the replaced function, passing in a `this` value. This ultimately causes the http2 module throw an error saying that a routine it is trying to use is undefined.

My solutions to this have been two approaches.  Originally I uses the `response` itself in place of `this` when I called `_write` and `_end` (the saved original routines), but I am currently defining the new function with a `.bind(response)` tacked on the end.

By doing this it is mostly working - I am trying to get it to also work with pushing stuff and I am getting occasional "Cant remove headers after they are sent", but that is another issue I think.

**Comment by akc42** [comment]
I include my version of the middleware.  It is modified a bit, in that in my specialised environment I can use filenames rather than a content-type header to know how to treat file. I am also using pure javascript, not coffee script, 

```
  function transformResponse(transformNeeded) {
    debug('setting up Transform Response');
    return (req, res, next) => {
      let ended = false;

      let _shouldTransform = null;
      let isHtml = true;

      // Note: this function memoizes its result.
      function shouldTransform() {
        if (_shouldTransform == null) {
          debug(`res statusCode = ${res.statusCode} for url ${req.url}`);
          const successful = res.statusCode >= 200 && res.statusCode < 300;
          debug('successful is ', successful);
          if (successful) {
            const result = transformNeeded(req);
            isHtml = result.isHtml;
            _shouldTransform = !!result.transform;
          } else {
            _shouldTransform = false;
          }
          debug('Should We Transform? ', _shouldTransform);
        }
        return _shouldTransform;
      }

      const chunks = [];

      const _write = res.write;

      res.write = function( chunk, enc, cb) {
        if (ended) {
          _write.call(this, chunk, enc, cb);
          return false;
        }
        if (shouldTransform()) {
          const buffer = (typeof chunk === 'string') ? new Buffer(chunk,enc) : chunk;
          chunks.push(buffer);
          return true;
        }
        return _write.call(this, chunk, enc, cb);
      }.bind(res);


      const _end = res.end;
      res.end = function (chunk, enc, cb) {
        if (ended)
          return false;
        ended = true;
        if (shouldTransform()) {
          if (chunk) {
            const buffer = (typeof chunk === 'string') ? new Buffer(chunk,enc) : chunk;
            chunks.push(buffer);
          }
          const body = Buffer.concat(chunks).toString('utf8');
          let newBody = body;
          try {
            newBody = transform(req, body, isHtml);
          } catch (e) {
            //eslint-disable-next-line no-console
            console.warn('Error', e);
          }
          // TODO(justinfagnani): re-enable setting of content-length when we know
          // why it was causing truncated files. Could be multi-byte characters.
          // Assumes single-byte code points!
          // res.setHeader('Content-Length', `${newBody.length}`);
          this.removeHeader('Content-Length');
          return _end.call(this, newBody);
        }
        return _end.call(this,chunk, enc, cb);
      }.bind(res);
      next();
    };
  }

```

**Comment by justinfagnani** [comment]
I don't think `write` and `end` should need to be bound like that, unless they are in the Response object being patched. According to JS method call semantics a method call is bound to the receiver automatically, and any code that tears off the method is responsible for calling it with the correct `this` value.

Do you have any stack traces for the original error? What's the value of `this` inside the patched functions when you see the error?

**Comment by akc42** [comment]
I don't have a stack trace right now, but I know the exact issue.  Inside the http2 module, the call to `response.end()` causes it almost immediately to call this._implicitHeaders() which is a prototype function of OutgoingMessage.  and without the bind (or calling `_end.call(res,chunk,enc,cb)` ) it falls over with undefined function.

Subsequent to raising this issue I have noticed that the coffee script for your middleware function actually seems to be set up slightly different, but I don't really understand coffee script so I sort of ignored it.

I did say my issue was tentative, and it might be the environment is somewhat different.  As long as I have raised it with you and you say its ok, then I'm fine with it.  My stuff now works in my environment but needs that bind.

I'll close the issue for now.

**Comment by justinfagnani** [comment]
FYI, we don't use CoffeeScript, but TypeScript which has all the same runtime semantics as JavaScript. That's not the issue here.

If you can make a reproduction, I'll fix it, but this kind of defensive binding shouldn't be necessary.
