### ISSUE TITLE
Last few releases miss a changelog on GitHub

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/polyserve#199]
After version 0.16.0, the changelogs are not updated on GitHub at https://github.com/Polymer/polyserve/releases Would be nice to have the changelogs there again

**Comment by aomarks** [comment]
@TimvdLippe @usergenic Do you know what determines whether the release has a changelog? Does it have to be done manually? We typically release with `np`, does that somehow automate parsing the CHANGELOG.md?

**Comment by TimvdLippe** [comment]
Seems like it does not: https://github.com/sindresorhus/np/issues/104

**Comment by TimvdLippe** [comment]
This was moved into the monorepo. The CHANGELOG is included there: https://github.com/Polymer/tools/releases/tag/polyserve%400.27.12
