### ISSUE TITLE
Read directory from .bowerrc

### ISSUE THREAD

**Issue by bendavis78** [Polymer/polyserve#27]
The .bowerrc file allows you to override your bower directory. The script should default to the configured directory.

**Comment by justinfagnani** [comment]
Bower has some strange (to me anyway) behavior around configuration, and reads it from a large variety of places. From http://bower.io/docs/config/#placement--order :

> The config is obtained by merging multiple configurations by this order of importance:
> 
> * CLI arguments via --config
> * Environment variables
> * Local .bowerrc located in the current working directory
> * All .bowerrc files upwards the directory tree
> * .bowerrc file located in user’s home folder (~)
> * .bowerrc file located in the global folder (/)

As crazy as this is to me, I think if we support `.bowerrc` we should support as much of this as possible, excluding the CLI arguments.

**Comment by indolering** [comment]
Few issues with Bower's directory handling:

1. Bower currently [doesn't support absolute paths](https://github.com/bower/bower/issues/1914). 
2. Bower interprets paths from the CWD of Bower, not the file.  So a `directory` setting in a parent `.bowerrc` file [will be treated as a path within the child directory](https://github.com/bower/bower/issues/1914#issuecomment-160227105).
3. Bower [will support](https://github.com/bower/bower/issues/1986) reading the `directory` variable from `bower.json` as well.  This will not inherit path directory settings from the parent.  

A fix is in the works for 1 & 2.

**Comment by Rayraegah** [comment]
My current bower config in .bowerrc is `"directory": "../bower_components"`. 

If there was a simple and easy way to tell polyserve to look for `bower_components` in the root dir it'll make my day.

**Comment by justinfagnani** [comment]
The main goal of polyserve is to get rid of dangerous workarounds like `"directory": "../bower_components"`, or the even more dangerous `"directory": "../"`, by letting a component directory be self-contained even as relative links appear to reach out of it.

While I do want to offer some flexibility in configuration, I also don't want to encourage the very practices that polyserve is trying to eliminate :)

**Comment by Rayraegah** [comment]
Well, it makes sense; because the server's root dir is the component / project folder. imo, I moved bower components a level up for convenience. 

**But** after thinking about it - I moved it back into the project folder so its self-contained.
