### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by indolering** [Polymer/polyserve#47]
Mixed content can cause problems in some browsers, it would be ideal if Polyserve came with a self-signed cert that could be added to the browser's trustbase.

**Comment by justinfagnani** [comment]
I'm far from a security expert, but I'd be wary about publishing a cert that's intended to be installed into a users browser. What about an option to use a cert supplied as a command-line flag?

**Comment by indolering** [comment]
It wouldn't be seeded into the trustbase automatically, for 99% of developers, "adding a cert to the trust base" translates into manually overriding a warning and (for Firefox users) saving a permanent exception that only be valid for the loopback address.  Furthermore, Polyserve would generate the cert during installation, so an attacker would need to have local access to your machine anyway.

**Comment by indolering** [comment]
The cert should be valid for localhost, 127.0.0.1, and 10.0.2.2.  The IE/Edge VMs use the latter address as a proxy for the host loopback address.

**Comment by tony19** [comment]
https://github.com/PolymerLabs/polyserve/pull/98 adds support for h2 and https. It generates the TLS key/cert for the user, so we don't need to provide one (although the PR supports specifying a key/cert if desired).

**Comment by abdonrd** [comment]
The #98 should have solved the HTTPS?

With `polymer serve --protocol h2 --manifest push-manifest.json`, I see:

<img width="664" alt="screen shot 2017-05-11 at 2 39 49 am" src="https://cloud.githubusercontent.com/assets/1007051/25927056/7c28812c-35f3-11e7-993b-7ecd688f5dbb.png">

**Comment by justinfagnani** [comment]
@abdonrd this is expected, as self-signed certs aren't actually trusted. They would need to be added to the browsers set of trusted certs manually.

**Comment by abdonrd** [comment]
Thanks @justinfagnani! I added the cert manually and marked as trusted:

<img width="876" alt="screen shot 2017-05-11 at 3 43 01 am" src="https://cloud.githubusercontent.com/assets/1007051/25928349/1802877a-35fc-11e7-8699-565d17639ed2.png">

And now the error is different: `NET::ERR_CERT_COMMON_NAME_INVALID`

<img width="1336" alt="screen shot 2017-05-11 at 3 40 16 am" src="https://cloud.githubusercontent.com/assets/1007051/25928377/376dbe5e-35fc-11e7-873c-3009f2747c06.png">

**Comment by justinfagnani** [comment]
There's also a flag to trust invalid certs from localhost. That's what I'm using.

**Comment by abdonrd** [comment]
@justinfagnani thanks! Only with `chrome://flags/#allow-insecure-localhost` works! :)
